### ISSUE TITLE
YAML: Interpret integer_list, long_list and real_list

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_simulator#27]
## Background

RSMP [defines the following data types](http://rsmp-nordic.org/rsmp_core/applicability/basic_structure.html?highlight=integer#return-values) for use in alarms, status and commands:
- string
- integer
- long
- real
- boolean
- base64

Each data field is either referred to as `rvs` (return values) or `arg` (arguments) in the specification. They typically use either a predefined list of allowed values or a `max` and `min` value. The max and min value was typically expressed as `[0-12]` in the `Value` column in the Excel SXL. When the YAML format was added, max and min were moved to its separate `min` and `max` fields.

Example of usage of `max` and `min` values:
```yaml
          vehicles:
            type: integer_list
            description: |
              Number of vehicles
              - Value expressed as an integer with a range of 0-65535.
              - Contains data from all detector logics. Each detector logic is separated with a comma.
              - The value is set to “-1” if no data could be measured (e.g. detector fault)
            min: -1
            max: 65535
```

Example of usage of a predefined list:
```yaml
          status:
            type: integer
            values:
              0: disabled
              1: dark mode
              2: yellow flash
```

## Data types used in the YAML file

Some of the statuses used by the SXL for Traffic Light Controllers (TLC) also have the ability to contain a comma separated list, e.g. "True,True". Comma separated lists were added in order to be able to send a value for each intersection connected to a single TLC. This extends the list of possible data types a little bit:
- integer_list
- long_list
- real_list

## Needed changes to the RSMP simulator

Right now, the RSMP Simulator interprets `integer_list` as `unknown`

The RSMP Simulator needs to interpret:
- `integer_list` and `integer`
- `long_list` as `long`
- `real_list` as `real`
